# Generated by Django 3.0.8 on 2020-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_author_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='Nalla jaguar', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='Toronto', max_length=60),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='John Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(default='Vancouver', max_length=30),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(default='www.google.com'),
        ),
    ]
