# Generated by Django 3.0.8 on 2020-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_todolist_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.CharField(choices=[('LT', 'Long Term'), ('ST', 'Short Term')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
