# Generated by Django 3.0.8 on 2020-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0008_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
