# Generated by Django 3.0.8 on 2020-08-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0009_auto_20200811_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
