# Generated by Django 3.0.8 on 2020-08-12 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0010_auto_20200811_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 3, 0, 36, 25396, tzinfo=utc)),
        ),
    ]
