# Generated by Django 3.0.8 on 2020-08-13 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0011_auto_20200811_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
