# Generated by Django 3.0.8 on 2020-08-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0012_auto_20200813_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-time']},
        ),
    ]
