# Generated by Django 3.0.8 on 2020-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200822_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='tid',
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
