# Generated by Django 3.0.8 on 2020-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200822_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
