# Generated by Django 3.0.8 on 2020-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles'),
        ),
    ]
